### ISSUE TITLE
TLS endpoint - failed to verify certificate

### ISSUE THREAD

**Issue by mschirrmeister** [albertito/prometheus-expvar-exporter#2]
If I have a TLS endpoint with a self signed certificate the connection fails with the following error.

```
2024/04/19 18:37:41 Error scraping "https://192.168.2.199:8443/routedns/vars": Get "https://192.168.2.199:8443/routedns/vars": tls: failed to verify certificate: x509: “server.acme.test” certificate is not standards compliant
```

Some tools have a command line switch to skip the verification or the possibility to configure a parameter in the config file. I have not seen anything in the code that this can be configured. Some go programs have something like:

```
tls_config:
  insecure_skip_verify: true
```

As a test I have added the following code to get around it. 
```
◆ prometheus-expvar-exporter git:(next) ✗ ❯❯❯ git diff main.go main.go.orig
diff --git a/main.go b/main.go
index 4a1db22..f1be1e7 100644
--- a/main.go
+++ b/main.go
@@ -12,6 +12,7 @@ import (
        "regexp"
        "strings"
        "unicode"
+       "crypto/tls"

        "github.com/pelletier/go-toml"
        "github.com/prometheus/client_golang/prometheus"
@@ -24,6 +25,12 @@ var (
 )

 func main() {
+        // https://stackoverflow.com/questions/12122159/how-to-do-a-https-request-with-bad-certificate
+        http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
+        _, err := http.Get("https://golang.org/")
+        if err != nil {
+            fmt.Println(err)
+        }
        flag.Parse()

        config, err := toml.LoadFile(*configPath)
```

Is it correct that there is currently no way to skip the verification?

**Comment by albertito** [comment]
> Is it correct that there is currently no way to skip the verification?

That is correct.

You can try commit 176c61fe708bccd914380fea7fe43714595efb28 (in the `next` branch) which adds an `insecure = true` option for this.

Let me know how it goes, and I will incorporate it into the `main` branch if it's working well.

Thank you!

**Comment by mschirrmeister** [comment]
It works great. No issues so far.

Muchas gracias. 😄
